export const imageTilesStyles = {
  root: (isMobile: boolean) => ({
    display: "grid",
    gridTemplateColumns: isMobile ? "1fr" : { xs: "1fr", sm: "repeat(2, 1fr)" },
    gap: { xs: 2, sm: 3, md: 4 },
    alignItems: "center",
    justifyItems: "center",
    gridAutoRows: "auto",
    width: "100%",
    px: { xs: 2, sm: 3, md: 4 },
  }),
  tile: {
    display: "flex",
    flexDirection: "column",
    height: "auto",
    maxHeight: 600,
    justifyContent: "center",
    textAlign: { xs: "center", sm: "left" },
    alignItems: { xs: "center", sm: "flex-start" },
    backgroundColor: "background.paper",
    padding: { xs: 0, md: 3 },
    boxSizing: "border-box" as const,
    borderRadius: 0,
    boxShadow: 0,
    width: "100%",
    overflow: "hidden",
    transition: "transform 0.18s ease, box-shadow 0.18s ease",
    "&:hover": {
      borderRadius: 2,
      transform: "translateY(-6px)",
      boxShadow: 6,
      backgroundColor: "background.paper",
    },
    position: "relative",
  },
  image: {
    width: "100%",
    height: "auto",
    maxHeight: { xs: 350, md: 600 },
    aspectRatio: "1",
    objectFit: "cover" as const,
    marginBottom: { xs: 1, sm: 1.5 },
    borderRadius: 1,
    display: "block",
    boxSizing: "border-box",
  },
  title: {
    marginBottom: { xs: 0.75, sm: 1 },
  },
  content: {
    color: "text.secondary",
  },
};
