export const inovationSectionStyles = {
  root: {
    pt: { xs: 3, sm: 5, md: 8 },
    pb: { xs: 2, sm: 4, md: 6 },
    display: "flex",
    width: "100%",
    flexDirection: "column",
    gap: { xs: 1.5, sm: 2, md: 4 },
    backgroundColor: "primary.main",
  },
  container: {
    gap: { xs: 1.5, sm: 2, md: 4 },
    display: "flex",
    flexDirection: "column",
    px: { xs: 2, sm: 3, md: 5, lg: 6 },
    py: { xs: 2, sm: 3, md: 6 },
    maxWidth: 1400,
    mx: 'auto',
    width: '100%',
  },
  textBox: {
    display: "flex",
    flexDirection: "column",
    gap: { xs: 2, sm: 3, md: 4 },
    mt: { xs: 2, sm: 3, md: 4 },
    mb: { xs: 2, sm: 3, md: 4 },
    textAlign: { xs: "center", md: "left" },
    alignItems: { xs: "center", md: "flex-start" },
  },
  image: {
    width: "100%",
    height: "auto",
    maxHeight: { xs: 300, sm: 400, md: 500 },
    objectFit: "cover" as const,
    objectPosition: "center",
    borderRadius: 2,
  },
};
