export const entrySectionStyles = {
  root: {
    flex: 1,
    backgroundColor: "secondary.main",
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    alignItems: { xs: "stretch", md: "center" },
    width: "100%",
    maxWidth: "100vw",
    minHeight: { xs: "auto", md: "100vh" },
    position: 'relative' as const,
    overflow: 'hidden',
  },
  textBox: {
    gap: { xs: 1.5, sm: 2, md: 4 },
    display: "flex",
    flexDirection: "column",
    px: { xs: 2, sm: 3, md: "6%", lg: "10%" },
    py: { xs: 3, sm: 4, md: 8 },
    alignItems: { xs: "center", md: "flex-start" },
    justifyContent: "center",
    textAlign: { xs: "center", md: "left" },
    width: { xs: "100%", md: "50%" },
    order: { xs: 2, md: 1 },
    position: 'relative' as const,
    zIndex: 1,
  },
  button: {
    borderRadius: 1,
    backgroundColor: "secondary.light",
    color: "secondary.contrastText",
    fontWeight: 600,
    px: { xs: 3, sm: 4 },
    py: { xs: 1.5, sm: 2 },
    fontSize: { xs: '0.9rem', sm: '1rem' },
    minHeight: 44,
    minWidth: 120,
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: "secondary.light",
      transform: 'translateY(-2px)',
      boxShadow: 3,
    },
    '&:focus-visible': {
      outline: '2px solid',
      outlineColor: 'secondary.contrastText',
      outlineOffset: 2,
    },
  },
  image: {
    width: { xs: "100%", md: "50%" },
    height: { xs: "30vh", sm: "40vh", md: "100vh" },
    minHeight: { xs: 220, sm: 280 },
    maxHeight: { xs: 350, sm: 480 },
    objectFit: "cover" as const,
    objectPosition: "center",
    order: { xs: 1, md: 2 },
    flexShrink: 0,
  },
};
