export const explorePortfolioStyles = {
  root: {
    width: "100%",
    height: { xs: 400, sm: 500, md: 600 },
    minHeight: 400,
    position: "relative" as const,
  },
  overlay: {
    width: "100%",
    height: "100%",
    position: "absolute" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    color: "white",
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    gap: { xs: 2, sm: 3, md: 4 },
    px: { xs: 3, sm: 4 },
    textAlign: 'center',
  },
  button: {
    backgroundColor: "secondary.light",
    color: "secondary.contrastText",
    opacity: 1,
    px: { xs: 3, sm: 4 },
    py: { xs: 1.5, sm: 2 },
    minHeight: 44,
    fontSize: { xs: '0.9rem', sm: '1rem' },
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: "secondary.light",
      transform: 'translateY(-2px)',
      boxShadow: 3,
    },
    '&:focus-visible': {
      outline: '2px solid white',
      outlineOffset: 2,
    },
  },
  backgroundImage: {
    width: "100%",
    objectFit: "cover" as const,
    backgroundImage:
      "url(https://media.gettyimages.com/id/1413283697/photo/writing-code-creating-website-dashboards-and-programming-help-for-technology-website-upkeep.jpg?b=1&s=2048x2048&w=0&k=20&c=uRu5fvA1eopJyvF5AiiQIOlK6xvaoHhBrucKIupMQdM=)",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100%",
  },
};
