export const empowerSolutionSectionStyles = {
  root: {
    backgroundColor: "secondary.main",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    minHeight: { xs: "auto", md: "450px" },
    py: { xs: 3, sm: 5, md: 8 },
    px: { xs: 2, sm: 3, md: 5 },
  },
  contentWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: { xs: "column", md: "row" },
    gap: { xs: 4, sm: 5, md: 6, lg: 8 },
    maxWidth: 1400,
    width: '100%',
  },
  imageBox: {
    flex: { xs: "1 1 100%", md: "0 0 45%" },
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: { xs: '100%', md: 'auto' },
  },
  image: {
    width: "100%",
    maxWidth: { xs: '100%', md: 600, lg: 800 },
    height: "auto",
    objectFit: "cover" as const,
    objectPosition: "center",
    borderRadius: 2,
  },
  textBox: {
    flex: { xs: "1 1 100%", md: "0 0 55%" },
    display: "flex",
    flexDirection: "column",
    gap: { xs: 2, sm: 2.5, md: 3 },
    width: { xs: '100%', md: 'auto' },
    textAlign: { xs: "center", md: "left" },
    alignItems: { xs: "center", md: "flex-start" },
  },
};
